In [400]:
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import csv
import sklearn 
import graphviz
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.feature_selection import SelectKBest, chi2, f_classif
from io import StringIO
import sklearn.tree as tree
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
import sqlite3
import pandas as pd
import numpy as np
import seaborn as sns
import itertools
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier 
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn import linear_model
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, accuracy_score
from sklearn.calibration import CalibratedClassifierCV
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import make_scorer
from time import time
from sklearn.decomposition import PCA, FastICA
from sklearn.pipeline import Pipeline
import warnings
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [401]:
#yi=traind.Age.values
#yi=yi.reshape(-1,1)
#imputer = KNNImputer(n_neighbors=5)
#ynew=imputer.fit_transform(yi)


In [402]:
traind=pd.read_csv('trainingdat.csv')
testd=pd.read_csv('testdat.csv')

In [403]:
traind=pd.read_csv('trainingdat.csv')[:-1];print(traind)

      ID        Date            Opponent Is_Home_or_Away  \
0    1.0    9/5/2015               Texas            Home   
1    2.0   9/12/2015            Virginia            Away   
2    3.0   9/19/2015         GeorgiaTech            Home   
3    4.0   9/26/2015               UMass            Home   
4    5.0   10/3/2015             Clemson            Away   
5    6.0  10/10/2015                Navy            Home   
6    7.0  10/17/2015                 USC            Home   
7    8.0  10/31/2015              Temple            Away   
8    9.0   11/7/2015                PITT            Away   
9   10.0  11/14/2015          WakeForest            Home   
10  11.0  11/21/2015       BostonCollege            Away   
11  12.0  11/28/2015            Stanford            Away   
12  13.0    9/4/2016               Texas            Away   
13  14.0   9/10/2016              Nevada            Home   
14  15.0   9/17/2016       MichiganState            Home   
15  16.0   9/24/2016                Duke

In [404]:
print(traind)

      ID        Date            Opponent Is_Home_or_Away  \
0    1.0    9/5/2015               Texas            Home   
1    2.0   9/12/2015            Virginia            Away   
2    3.0   9/19/2015         GeorgiaTech            Home   
3    4.0   9/26/2015               UMass            Home   
4    5.0   10/3/2015             Clemson            Away   
5    6.0  10/10/2015                Navy            Home   
6    7.0  10/17/2015                 USC            Home   
7    8.0  10/31/2015              Temple            Away   
8    9.0   11/7/2015                PITT            Away   
9   10.0  11/14/2015          WakeForest            Home   
10  11.0  11/21/2015       BostonCollege            Away   
11  12.0  11/28/2015            Stanford            Away   
12  13.0    9/4/2016               Texas            Away   
13  14.0   9/10/2016              Nevada            Home   
14  15.0   9/17/2016       MichiganState            Home   
15  16.0   9/24/2016                Duke

In [405]:
traind.Is_Opponent_in_AP25_Preseason = traind.Is_Opponent_in_AP25_Preseason.map( {'In': 1, 'Out': 0})
traind.Media = traind.Media.map( {'1-NBC':0, '2-ESPN':1, '3-FOX':2, '4-ABC': 3, '5-CBS': 4})
traind.Is_Home_or_Away = traind.Is_Home_or_Away.map( {'Home': 1, 'Away': 0})
traind.Label = traind.Label.map( {'Win': 1, 'Lose': 0})

X = traind[['Is_Home_or_Away','Media','Is_Opponent_in_AP25_Preseason']]
y = traind['Label']

                                                            

In [406]:
print(X,y)

    Is_Home_or_Away  Media  Is_Opponent_in_AP25_Preseason
0                 1      0                              0
1                 0      3                              0
2                 1      0                              1
3                 1      0                              0
4                 0      3                              1
5                 1      0                              0
6                 1      0                              1
7                 0      3                              0
8                 0      3                              0
9                 1      0                              0
10                0      0                              0
11                0      2                              1
12                0      3                              0
13                1      0                              0
14                1      0                              0
15                1      0                              0
16            

In [407]:

model = GaussianNB()
model.fit(X, y); 

In [408]:
y_pred = model.predict(X)
classification_report(y,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.62      0.80      0.70        10\n           1       0.82      0.64      0.72        14\n\n    accuracy                           0.71        24\n   macro avg       0.72      0.72      0.71        24\nweighted avg       0.73      0.71      0.71        24\n'

In [409]:
accuracy_score(y, y_pred)

0.7083333333333334

In [410]:
recall_score(y, y_pred)

0.6428571428571429

In [411]:
precision_score(y, y_pred)

0.8181818181818182

In [412]:
f1_score(y, y_pred)

0.7200000000000001

In [413]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)
y_pred1 = neigh.predict(X)

In [414]:
accuracy_score(y, y_pred1)

0.7083333333333334

In [415]:
recall_score(y, y_pred1)

1.0

In [416]:
precision_score(y, y_pred1)

0.6666666666666666

In [417]:
f1_score(y, y_pred1)

0.8

In [418]:
y_pred1

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0], dtype=int64)

In [419]:
y_pred

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0], dtype=int64)

In [420]:
testd.Is_Opponent_in_AP25_Preseason = testd.Is_Opponent_in_AP25_Preseason.map( {'In': 1, 'Out': 0})
testd.Media = testd.Media.map( {'1-NBC':0, '2-ESPN':1, '3-FOX':2, '4-ABC': 3, '5-CBS': 4})
testd.Is_Home_or_Away = testd.Is_Home_or_Away.map( {'Home': 1, 'Away': 0})
testd.Label = testd.Label.map( {'Win': 1, 'Lose': 0})

X1 = testd[['Is_Home_or_Away','Media','Is_Opponent_in_AP25_Preseason']]
y1 = testd['Label']
print(X1,y1)

    Is_Home_or_Away  Media  Is_Opponent_in_AP25_Preseason
0                 1      0                              0
1                 1      0                              1
2                 0      1                              0
3                 0      2                              0
4                 1      0                              0
5                 0      3                              0
6                 1      0                              1
7                 1      0                              0
8                 1      0                              0
9                 0      3                              1
10                1      0                              0
11                0      3                              1 0     1
1     0
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     0
10    1
11    0
Name: Label, dtype: int64


In [421]:
modelt = GaussianNB()
modelt.fit(X1, y1); 
y_pred2 = model.predict(X1)


In [422]:
accuracy_score(y1, y_pred2)

0.8333333333333334

In [423]:
recall_score(y1, y_pred2)

0.7777777777777778

In [424]:
precision_score(y1, y_pred2)

1.0

In [425]:
f1_score(y1, y_pred2)

0.8750000000000001

In [426]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X1, y1)
y_pred3 = neigh.predict(X1)

In [427]:
accuracy_score(y1, y_pred3)

0.9166666666666666

In [428]:
recall_score(y1, y_pred3)

1.0

In [429]:
precision_score(y1, y_pred3)

0.9

In [430]:
f1_score(y1, y_pred3)

0.9473684210526316

In [431]:
y_pred2

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0], dtype=int64)

In [432]:
y_pred3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=int64)

In [433]:
for x,y,z in zip(y1.values,y_pred2,y_pred3):
    print(x,y,z)

1 1 1
0 0 1
1 1 1
1 1 1
1 1 1
1 0 1
1 0 1
1 1 1
1 1 1
0 0 0
1 1 1
0 0 0
